import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Project from "@/components/Project/Project";
import { Tag } from "../utils/Tag";
import Image from "next/image";
import vercel from "../../public/vercel.svg";
import Navbar from "@/components/Navbar/Navbar";

export default function Home() {
	return (
		<>
			<Head>
				<title>Evan Marian</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar></Navbar>
			<main className={styles.main}>
				<div className={styles.columns}>
					<div className={`${styles.column} ${styles.column1}`}>
						<div className={styles.title}>Greeting, Name.</div>
						<div className={styles.text}>
							Lorem ipsum dolor, sit amet consectetur adipisicing elit. Maiores
							deserunt, repudiandae, doloremque vero hic excepturi sint possimus
							aliquam provident reprehenderit porro amet, labore ipsam beatae
							exercitationem. Velit corrupti ea vitae?
						</div>
						<button className={`${styles.primary} ${styles.solid}`}>
							See my work
						</button>
						<button className={`${styles.primary} ${styles.hollow}`}>
							my Resume
						</button>
					</div>
					<div className={`${styles.column} ${styles.column2}`}>
						<div className={styles.title}>Column 2</div>
					</div>
				</div>
			</main>
			<Project
				title="Title"
				description="Lorem ipsum dolor sit, amet consectetur adipisicing elit. Fugiat illo provident eligendi totam facere, fugit quas enim porro voluptatibus voluptates fuga ducimus sed dolorem aspernatur suscipit sunt dicta at rem."
				img="https://via.placeholder.com/500"
				tags={[Tag.Tag1, Tag.Tag2]}
			/>
		</>
	);
}
