import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Project from "@/components/Project/Project";
import { Tag } from "../utils/Tag";
import Image from "next/image";
import vercel from "../../public/vercel.svg";
import Navbar from "@/components/Navbar/Navbar";
import Skill, {SkillLevel} from "@/components/Skill/Skill";

export default function Home() {
	return (
		<>
			<Head>
				<title>Evan Marian</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar></Navbar>
			<Skill name="Skill 1" level={SkillLevel.Low}></Skill>
			<Skill name="Skill 2" level={SkillLevel.MediumHigh}></Skill>
			<Project
				title="Title"
				description="Lorem ipsum dolor sit, amet consectetur adipisicing elit. Fugiat illo provident eligendi totam facere, fugit quas enim porro voluptatibus voluptates fuga ducimus sed dolorem aspernatur suscipit sunt dicta at rem."
				img="https://via.placeholder.com/500"
				tags={[Tag.Tag1, Tag.Tag2]}
			/>
		</>
	);
}
