import styles from "@/styles/Projects.module.css";
import Head from "next/head";
import Project from "@/components/Project/Project";
import { ProjectProps } from "@/components/Project/Project";
import projects from "../../utils/projects";
import Navbar from "@/components/Navbar/Navbar";

export default function Projects() {
	return (
		<>
			<Head>
				<title>Evan Marian</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar></Navbar>
			<main>
				<div className={styles.title}>Projects.</div>
				<div className={styles.projects}>
					{projects.map((projectProps: ProjectProps, i) => (
						<Project {...projectProps} key={i}></Project>
					))}
				</div>
			</main>
		</>
	);
}
